name: ci

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '**.zig'
      - '**.zon'
      - '**.c'
      - '**.h'
  workflow_dispatch:

# This cancels older workflow runs on pull requests while ensuring that there
# are no concurrency limits on pushes and manual workflow dispatches.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  build:
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        host:
          - aarch64-macos
          - x86_64-freebsd
          - x86_64-linux
          - x86_64-windows

    # https://codeberg.org/Codeberg/Community/issues/2320
    runs-on: ${{ fromJSON(format('["self-hosted", "{0}"]', matrix.host)) }}

    steps:
      - name: Checkout
        uses: https://codeberg.org/ziglang/checkout@19af6bac491e2534a4687a50ee84fa7f13258d28

      - name: Setup Zig
        uses: https://codeberg.org/mlugg/setup-zig@e7d1537c378b83b8049f65dda471d87a2f7b2df2

      - name: Build
        run: zig build --maxrss ${{ env.ZSF_MAX_RSS }}

      - name: Build 32-bit FreeBSD
        if: matrix.host == 'x86_64-freebsd'
        run: zig build --maxrss ${{ env.ZSF_MAX_RSS }} -Dtarget=arm-freebsd

      - name: Build 32-bit Linux
        if: matrix.host == 'x86_64-linux'
        run: zig build --maxrss ${{ env.ZSF_MAX_RSS }} -Dtarget=arm-linux

      - name: Run Tests
        run: |
          zig build test --maxrss ${{ env.ZSF_MAX_RSS }} -Doptimize=Debug
          zig build test --maxrss ${{ env.ZSF_MAX_RSS }} -Doptimize=ReleaseFast

      - name: Run Tests MSVC
        if: matrix.host == 'x86_64-windows'
        run: |
          zig build test --maxrss ${{ env.ZSF_MAX_RSS }} -Dtarget=native-windows-msvc -Doptimize=Debug
          zig build test --maxrss ${{ env.ZSF_MAX_RSS }} -Dtarget=native-windows-msvc -Doptimize=ReleaseFast

      - name: Run Cross-Translation Tests
        run: zig build test --maxrss ${{ env.ZSF_MAX_RSS }} -Doptimize=Debug -Dtest-cross-targets

      - name: Run Examples
        run: zig build all --maxrss ${{ env.ZSF_MAX_RSS }} --build-file examples/build.zig
