name: ci

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '**.zig'
      - '**.zon'
      - '**.c'
      - '**.h'
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  build:
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        host:
          - aarch64-macos
          - x86_64-linux
          - x86_64-windows

    runs-on:
      - self-hosted
      - ${{ matrix.host }}

    steps:
      - uses: https://codeberg.org/ziglang/checkout@19af6bac491e2534a4687a50ee84fa7f13258d28

      - uses: https://codeberg.org/mlugg/setup-zig@fixes
        with:
          # The cache reuse logic in setup-zig is only safe in a container.
          use-cache: false

      - name: Build
        run: zig build

      - name: Build 32-bit
        if: matrix.host == 'x86_64-linux'
        run: zig build -Dtarget=arm-linux

      - name: Run Tests
        run: |
          zig build test -Doptimize=Debug
          zig build test -Doptimize=ReleaseFast

      - name: Run Tests MSVC
        if: matrix.host == 'x86_64-windows'
        run: |
          zig build test -Dtarget=native-windows-msvc -Doptimize=Debug
          zig build test -Dtarget=native-windows-msvc -Doptimize=ReleaseFast

      - name: Run Cross-Translation Tests
        run: zig build test -Doptimize=Debug -Dtest-cross-targets

      - name: Run Examples
        run: zig build all --build-file examples/build.zig
